# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      # check file system problems
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks

      # unify whitespace and line ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending

      # sort requirements.txt files
      - id: requirements-txt-fixer

      # python code
      - id: check-docstring-first
      - id: fix-encoding-pragma

      # check more
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: check-merge-conflict

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: c0af833f6d540aa5ede2bf64d6bb8ce552c3cfce  # frozen: v0.21
    hooks:
      - id: validate-pyproject
        files: pyproject.toml$

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 1a92c0953500d402fc49ceb67ad7fbf7cabad38a  # frozen: 3.0.3
    hooks:
      - id: editorconfig-checker
        alias: ec
        args:
          - "--disable-indent-size"

  - repo: https://github.com/google/yapf
    rev: 3e6cd99b6652cd00867b86e5e82a1dbccc5c0f72  # frozen: v0.40.2
    hooks:
      - id: yapf
        exclude: /ui_[^/]+\.py$|_res.py$
        additional_dependencies:
          - "toml"

  - repo: https://github.com/pycqa/isort
    rev: c235f5e450b4b84e58d114ed4c589cbf454175a3  # frozen: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        exclude: /ui_[^/]+\.py$|_res.py$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "f12edd9c7be1c20cfa42420fd0e6df71e42b51ea"  # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier

  - repo: https://github.com/rstcheck/rstcheck
    rev: "f30c4d170a36ea3812bceb5f33004afc213bd797"  # frozen: v6.2.4
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx]
        args: ["--config", "docs/rstcheck.cfg"]

  - repo: https://github.com/klen/pylama
    rev: 7c81c74765768aa92a379cc37b7508f7c83c4dd3 # frozen: 8.4.1
    hooks:
      - id: pylama
        exclude: /ui_[^/]+\.py$|_res.py$

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 17a61c4f7a7cd6a28daa5c4b88c725030e45e641 # frozen: v1.0.1
  #   hooks:
  #     - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: "36fd65054fc8864b4037d0918904f9331512feb5"  # frozen: 1.7.10
    hooks:
      - id: bandit
        files: "python/ectec-gui/src/"
        args:
          - "--aggregate"
          - "vuln"
          - "-ll"
          - "-q"
          - "-f"
          - "custom"
          - "--msg-template"
          - "--------------------------------------------------\n
            {relpath}:{line}:\n
            [{test_id:^8}] Severity: {severity} Confidence: {confidence}\n
            {msg}"

# configuration for the pre-commit.ci bot
# only relevant when actually using the bot
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci, https://pre-commit.com and
    the `.pre-commit-config.yaml` file in this repository.

  autofix_prs: true # default
  autoupdate_branch: "develop"
  autoupdate_commit_msg: |
    [pre-commit.ci] Autoupdate pre-commit hook versions.

    for more information, see https://pre-commit.ci, https://pre-commit.com and
    the `.pre-commit-config.yaml` file in this repository.

  submodules: false # default
