# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chattool.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 753)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.messageEntry = QtWidgets.QTextEdit(self.centralwidget)
        self.messageEntry.setGeometry(QtCore.QRect(10, 660, 451, 41))
        self.messageEntry.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.messageEntry.setObjectName("messageEntry")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(470, 660, 121, 41))
        self.sendButton.setObjectName("sendButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 581, 631))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chatHistory = QtWidgets.QGroupBox(self.centralwidget)
        self.chatHistory.setGeometry(QtCore.QRect(600, 10, 361, 701))
        self.chatHistory.setObjectName("chatHistory")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 21))
        self.menubar.setObjectName("menubar")
        self.menuServer = QtWidgets.QMenu(self.menubar)
        self.menuServer.setObjectName("menuServer")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuRSA = QtWidgets.QMenu(self.menubar)
        self.menuRSA.setObjectName("menuRSA")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionChange_settings = QtWidgets.QAction(MainWindow)
        self.actionChange_settings.setObjectName("actionChange_settings")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.menuServer.addAction(self.actionInfo)
        self.menuSettings.addAction(self.actionChange_settings)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuServer.menuAction())
        self.menubar.addAction(self.menuRSA.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA - Chattool"))
        self.sendButton.setText(_translate("MainWindow", "Send Message"))
        self.chatHistory.setTitle(_translate("MainWindow", "Keys"))
        self.menuServer.setTitle(_translate("MainWindow", "Server"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuRSA.setTitle(_translate("MainWindow", "RSA"))
        self.actionChange_settings.setText(_translate("MainWindow", "Change settings"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
