name: Run python tests for `ectec`

on:
  push:
    paths:
      - 'python/ectec-gui/src/ectec/**'
      - 'python/ectec-gui/tests/**'
  pull_request:
    paths:
      - 'python/ectec-gui/src/ectec/**'
      - 'python/ectec-gui/tests/**'
  

jobs:

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    name: Ectec tests Py${{ matrix.python-version }}, ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -U setuptools
          pip install -U wheel

      - name: Install `ectec` in develop mode
        run: pip install -e .
        working-directory: ./python/ectec-gui/

      - name: Run tests
        run: python -m tests
        working-directory: ./python/ectec-gui/
