name: Run python tests for `ectec`

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - "python/ectec-gui/src/ectec/**"
      - "python/ectec-gui/tests/**"
  pull_request:
    paths:
      - "python/ectec-gui/src/ectec/**"
      - "python/ectec-gui/tests/**"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]

    name: Ectec tests Py${{ matrix.python-version }}, ${{ matrix.os }}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -U setuptools
          pip install -U wheel

      - name: Install `ectec` in develop mode
        run: pip install -e .
        working-directory: ./python/ectec-gui/

      - name: Run tests
        run: python -m tests
        working-directory: ./python/ectec-gui/
