name: Run python tests for `ectec`

on:
  workflow_call:
  workflow_dispatch:
  push:
    paths:
      - "python/ectec-gui/src/ectec/**"
      - "python/ectec-gui/tests/**"
  pull_request:
    paths:
      - "python/ectec-gui/src/ectec/**"
      - "python/ectec-gui/tests/**"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]

    name: Ectec tests Py${{ matrix.python-version }}, ${{ matrix.os }}
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -U setuptools
          pip install -U wheel

      - name: Install `ectec` in develop mode
        run: pip install -e .
        working-directory: ./python/ectec-gui/

      - name: Run tests
        run: python -m tests
        working-directory: ./python/ectec-gui/
